### ISSUE TITLE
F-16 empty waypoint issue

### ISSUE THREAD

**Issue by JTFF-Nardio** [the-paid-actor/dcs-dtc#85]
It is no more possible to add empty waypoint like N 00°00.000’ E 000°00.000’. It generates this stacktrace : 

System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex')
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex)
   at DTC.Utilities.Coordinate.<ToDegreesMinutesDecimal>g__formatLatLong|13_0(CoordinatePart part, Int32 leadingDegZeros, <>c__DisplayClass13_0&) in D:\a\dcs-dtc\dcs-dtc\dcs-dtc\Utilities\Coordinate.cs:line 114
   at DTC.Utilities.Coordinate.ToDegreesMinutesDecimal(Int32 roundDigits) in D:\a\dcs-dtc\dcs-dtc\dcs-dtc\Utilities\Coordinate.cs:line 120
   at DTC.Utilities.Coordinate.ToDegreesMinutesThousandths() in D:\a\dcs-dtc\dcs-dtc\dcs-dtc\Utilities\Coordinate.cs:line 134
   at DTC.UI.Aircrafts.F16.WaypointEdit.SaveWaypoint() in D:\a\dcs-dtc\dcs-dtc\dcs-dtc\UI\Aircrafts\F16\WaypointEdit.cs:line 323
   at DTC.UI.Aircrafts.F16.WaypointEdit.btnSave_Click(Object sender, EventArgs e) in D:\a\dcs-dtc\dcs-dtc\dcs-dtc\UI\Aircrafts\F16\WaypointEdit.cs:line 95
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

Empty waypoint are very usefull to allow the pilot to obtain non-continuous waypoint sequences (with seperations). 
Befor it was possible to do it like this : 
![image](https://github.com/the-paid-actor/dcs-dtc/assets/153278058/996a7382-ef74-4851-87c9-46d1d92539a2)
![image](https://github.com/the-paid-actor/dcs-dtc/assets/153278058/4d49a14f-434d-46c3-8374-d406a9b6e047)

DCS allow it ! Please can you fix it ?

Thank you.

**Comment by the-paid-actor** [comment]
Check V7 published today
